# Generated by Django 4.2.29 on 2026-04-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcustomization',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_history', to='core.subscription'),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_history', to='core.tenant'),
        ),
    ]
