# Generated by Django 4.2.29 on 2026-04-06 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='core.tenant')),
            ],
            options={
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, verbose_name='Warehouse Code')),
                ('warehouse_type', models.CharField(choices=[('distribution_center', 'Distribution Center'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('cold_storage', 'Cold Storage'), ('cross_dock', 'Cross-Dock')], default='distribution_center', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('zone_type', models.CharField(choices=[('receiving', 'Receiving'), ('storage', 'Storage'), ('shipping', 'Shipping'), ('staging', 'Staging'), ('cross_dock', 'Cross-Dock'), ('quarantine', 'Quarantine')], default='storage', max_length=20)),
                ('temperature_controlled', models.BooleanField(default=False)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum temperature in Celsius', max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum temperature in Celsius', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['warehouse', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('levels', models.PositiveIntegerField(default=1, help_text='Number of shelf levels')),
                ('max_weight_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight capacity in kg', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='warehousing.aisle')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='core.tenant')),
            ],
            options={
                'ordering': ['aisle', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CrossDockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='CD Number')),
                ('source', models.CharField(help_text='Source / origin of goods', max_length=255)),
                ('destination', models.CharField(help_text='Destination for goods', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('at_dock', 'At Dock'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('scheduled_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('scheduled_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('dock_door', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cross_dock_orders', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_dock_orders', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='CrossDockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cross_dock_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehousing.crossdockorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cross_dock_items', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_dock_items', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='aisle',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='warehousing.zone'),
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('bin_type', models.CharField(choices=[('standard', 'Standard'), ('bulk', 'Bulk'), ('pick', 'Pick'), ('pallet', 'Pallet'), ('cold', 'Cold'), ('hazmat', 'Hazmat')], default='standard', max_length=20)),
                ('max_weight', models.DecimalField(decimal_places=2, default=0, help_text='Maximum weight capacity in kg', max_digits=10)),
                ('max_volume', models.DecimalField(decimal_places=2, default=0, help_text='Maximum volume capacity in cubic meters', max_digits=10)),
                ('max_quantity', models.PositiveIntegerField(default=0, help_text='Maximum number of items')),
                ('current_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rack', models.ForeignKey(blank=True, help_text='Leave empty for floor bins', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='warehousing.rack')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='core.tenant')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='warehousing.zone')),
            ],
            options={
                'verbose_name_plural': 'bins',
                'ordering': ['zone', 'code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='aisle',
            unique_together={('tenant', 'code')},
        ),
    ]
