# Generated by Django 4.2.29 on 2026-04-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehousing', '0001_initial'),
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition_number', models.CharField(max_length=20, verbose_name='Disposition Number')),
                ('decision', models.CharField(choices=[('restock', 'Restock to Inventory'), ('repair', 'Send to Repair'), ('liquidate', 'Liquidate'), ('scrap', 'Scrap / Destroy'), ('return_to_vendor', 'Return to Vendor')], default='restock', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(max_length=20, verbose_name='RMA Number')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('return_address', models.TextField(blank=True, default='')),
                ('reason', models.CharField(choices=[('defective', 'Defective / Damaged'), ('wrong_item', 'Wrong Item Shipped'), ('not_as_described', 'Not as Described'), ('customer_change', 'Customer Changed Mind'), ('warranty', 'Warranty Claim'), ('expired', 'Expired / Near Expiry'), ('other', 'Other')], default='defective', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('requested_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rmas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rmas', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_authorizations', to='orders.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_authorizations', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_authorizations', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'rma_number')},
            },
        ),
        migrations.CreateModel(
            name='ReturnAuthorizationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('qty_requested', models.PositiveIntegerField(default=1)),
                ('qty_received', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='catalog.product')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnauthorization')),
                ('sales_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.salesorderitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_authorization_items', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(max_length=20, verbose_name='Inspection Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('overall_result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('partial', 'Partial')], default='', max_length=20)),
                ('inspected_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_inspections', to=settings.AUTH_USER_MODEL)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='returns.returnauthorization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_inspections', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'inspection_number')},
            },
        ),
        migrations.CreateModel(
            name='ReturnInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_inspected', models.PositiveIntegerField(default=0)),
                ('qty_passed', models.PositiveIntegerField(default=0)),
                ('qty_failed', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('good', 'Good / Like New'), ('minor_damage', 'Minor Damage'), ('major_damage', 'Major Damage'), ('missing_parts', 'Missing Parts'), ('defective', 'Defective'), ('unusable', 'Unusable / Scrap')], default='good', max_length=20)),
                ('restockable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returninspection')),
                ('rma_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_items', to='returns.returnauthorizationitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_inspection_items', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DispositionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposition_items', to='warehousing.bin')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.disposition')),
                ('inspection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposition_items', to='returns.returninspectionitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposition_items', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposition_items', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='disposition',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositions', to='returns.returninspection'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_dispositions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disposition',
            name='rma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='returns.returnauthorization'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='warehousing.warehouse'),
        ),
        migrations.CreateModel(
            name='RefundCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(max_length=20, verbose_name='Refund Number')),
                ('type', models.CharField(choices=[('refund', 'Refund'), ('credit_note', 'Credit Note'), ('store_credit', 'Store Credit'), ('exchange', 'Exchange')], default='refund', max_length=20)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('store_credit', 'Store Credit'), ('cheque', 'Cheque'), ('other', 'Other')], default='card', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='returns.returnauthorization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_credits', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'refund_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='disposition',
            unique_together={('tenant', 'disposition_number')},
        ),
    ]
