# Generated by Django 4.2.29 on 2026-04-10 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehousing', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=20, verbose_name='Lot Number')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Initial Quantity')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Available Quantity')),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier_batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('quarantine', 'Quarantine'), ('expired', 'Expired'), ('consumed', 'Consumed'), ('recalled', 'Recalled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lots', to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_batches', to='receiving.goodsreceiptnote', verbose_name='Goods Receipt Note')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_batches', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_batches', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_batches', to='warehousing.warehouse')),
            ],
            options={
                'verbose_name': 'Lot / Batch',
                'verbose_name_plural': 'Lots / Batches',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'lot_number')},
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('scrapped', 'Scrapped')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_serials', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='lot_tracking.lotbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='core.tenant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('approaching', 'Approaching Expiry'), ('expired', 'Expired'), ('recalled', 'Recalled')], max_length=20)),
                ('alert_date', models.DateField()),
                ('days_before_expiry', models.IntegerField(default=0)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_expiry_alerts', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='lot_tracking.lotbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceabilityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_number', models.CharField(max_length=20, verbose_name='Log Number')),
                ('event_type', models.CharField(choices=[('received', 'Received'), ('transferred', 'Transferred'), ('adjusted', 'Adjusted'), ('sold', 'Sold'), ('returned', 'Returned'), ('recalled', 'Recalled'), ('scrapped', 'Scrapped'), ('expired', 'Expired')], max_length=20)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_from', to='warehousing.warehouse')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traceability_logs', to='lot_tracking.lotbatch')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traceability_actions', to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traceability_logs', to='lot_tracking.serialnumber')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_logs', to='core.tenant')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_to', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'log_number')},
            },
        ),
    ]
