# Generated by Django 4.2.29 on 2026-04-17 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotbatch',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Initial Quantity'),
        ),
    ]
