# Generated by Django 4.2.29 on 2026-04-18 21:01

import core.state_machine
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('vendors', '0002_alter_vendor_minimum_order_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_alter_product_height_alter_product_length_and_more'),
        ('warehousing', '0001_initial'),
        ('receiving', '0001_initial'),
        ('lot_tracking', '0002_alter_lotbatch_quantity'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Route Code')),
                ('name', models.CharField(max_length=200)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower = higher priority.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('putaway_zone', models.ForeignKey(blank=True, help_text='Destination zone after QC pass.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_putaway_routes', to='warehousing.zone')),
                ('qc_zone', models.ForeignKey(help_text='Zone where items are held pending QC.', on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspection_routes', to='warehousing.zone')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_routes', to='warehousing.warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_routes', to='core.tenant')),
            ],
            options={
                'ordering': ['priority', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QCChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Checklist Code')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('applies_to', models.CharField(choices=[('all', 'All Products'), ('product', 'Specific Product'), ('vendor', 'Specific Vendor'), ('category', 'Specific Category')], default='all', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_checklists', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qc_checklists', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_checklists', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_checklists', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_checklists', to='vendors.vendor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QuarantineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarantine_number', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(choices=[('defect', 'Defect'), ('expiry', 'Approaching Expiry / Expired'), ('contamination', 'Contamination'), ('damage', 'Damage'), ('vendor_issue', 'Vendor Issue'), ('other', 'Other')], default='defect', max_length=20)),
                ('reason_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active Hold'), ('under_review', 'Under Review'), ('released', 'Released'), ('scrapped', 'Scrapped')], default='active', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_disposition', models.CharField(blank=True, choices=[('return_to_stock', 'Return to Stock'), ('rework', 'Rework'), ('scrap', 'Scrap'), ('return_to_vendor', 'Return to Vendor')], default='', max_length=20)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_records', to='receiving.goodsreceiptnote')),
                ('held_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_holds_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_records', to='lot_tracking.lotbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantine_records', to='catalog.product')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_holds_released', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_records', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantine_records', to='warehousing.warehouse')),
                ('zone', models.ForeignKey(help_text='Quarantine zone holding this item.', on_delete=django.db.models.deletion.PROTECT, related_name='quarantine_records', to='warehousing.zone')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'quarantine_number')},
            },
            bases=(core.state_machine.StateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QCChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('check_name', models.CharField(max_length=200)),
                ('check_type', models.CharField(choices=[('visual', 'Visual Inspection'), ('measurement', 'Measurement'), ('boolean', 'Yes / No'), ('text', 'Free Text'), ('photo', 'Photo Required')], default='visual', max_length=20)),
                ('expected_value', models.CharField(blank=True, default='', max_length=200)),
                ('is_critical', models.BooleanField(default=False, help_text='Failing a critical item auto-quarantines the item.')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality_control.qcchecklist')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_checklist_items', to='core.tenant')),
            ],
            options={
                'ordering': ['checklist', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRouteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to', models.CharField(choices=[('all', 'All Items'), ('product', 'Specific Product'), ('vendor', 'Specific Vendor'), ('category', 'Specific Category')], default='all', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_route_rules', to='catalog.category')),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_rules', to='quality_control.qcchecklist')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_route_rules', to='catalog.product')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='quality_control.inspectionroute')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_route_rules', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_route_rules', to='vendors.vendor')),
            ],
            options={
                'ordering': ['route', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_number', models.CharField(max_length=20)),
                ('quantity_affected', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('defect_type', models.CharField(choices=[('visual', 'Visual / Cosmetic'), ('functional', 'Functional'), ('packaging', 'Packaging'), ('labeling', 'Labeling'), ('expiry', 'Expiry'), ('contamination', 'Contamination'), ('other', 'Other')], default='visual', max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('receiving', 'Receiving / Inspection'), ('stocktaking', 'Stocktaking / Cycle Count'), ('customer_return', 'Customer Return'), ('production', 'Production'), ('other', 'Other')], default='receiving', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('scrapped', 'Scrapped')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_reports', to='receiving.goodsreceiptnote')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_reports', to='lot_tracking.lotbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_reports', to='catalog.product')),
                ('quarantine_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_reports', to='quality_control.quarantinerecord')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_defects', to=settings.AUTH_USER_MODEL)),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_reports', to='lot_tracking.serialnumber')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_reports', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'defect_number')},
            },
            bases=(core.state_machine.StateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DefectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quality_control/defect_photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('defect_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='quality_control.defectreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_photos', to='core.tenant')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_number', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.CharField(max_length=200)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted')], default='pending', help_text='Mirror of approval_status for StateMachineMixin.', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scrap_writeoffs', to=settings.AUTH_USER_MODEL)),
                ('defect_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_writeoffs', to='quality_control.defectreport')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_scrap_writeoffs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrap_writeoffs', to='catalog.product')),
                ('quarantine_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_writeoffs', to='quality_control.quarantinerecord')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_scrap_writeoffs', to=settings.AUTH_USER_MODEL)),
                ('stock_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_scrap_writeoffs', to='inventory.stockadjustment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_writeoffs', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrap_writeoffs', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'scrap_number')},
            },
            bases=(core.state_machine.StateMachineMixin, models.Model),
        ),
    ]
