# Generated by Django 4.2.29 on 2026-04-20 18:32

import django.core.validators
from django.db import migrations, models
import quality_control.models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectphoto',
            name='image',
            field=models.ImageField(upload_to='quality_control/defect_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), quality_control.models.validate_defect_photo_size, quality_control.models.validate_defect_photo_magic]),
        ),
    ]
