# Generated by Django 4.2.29 on 2026-04-20 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehousing', '0001_initial'),
        ('catalog', '0002_alter_product_height_alter_product_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=20, verbose_name='Report #')),
                ('report_type', models.CharField(choices=[('valuation', 'Inventory Valuation'), ('aging', 'Aging Analysis'), ('abc', 'ABC Analysis'), ('turnover', 'Stock Turnover Ratio'), ('reservations', 'Reservations Report'), ('multi_location', 'Multi-Location Stock Roll-up'), ('po_summary', 'Purchase Order Summary'), ('vendor_performance', 'Vendor Performance'), ('three_way_match', 'Three-Way Match Variance'), ('receiving_grn', 'Receiving / GRN'), ('stock_transfers', 'Stock Transfers'), ('stocktake_variance', 'Stocktaking Variance'), ('quality_control', 'Quality Control'), ('scrap_writeoff', 'Scrap Write-Off'), ('so_summary', 'Sales Order Summary'), ('fulfillment', 'Fulfillment (Pick/Pack/Ship)'), ('shipment_carrier', 'Shipment / Carrier'), ('returns_rma', 'Returns (RMA)'), ('lot_expiry', 'Lot / Serial / Expiry'), ('forecast_vs_actual', 'Forecast vs Actual'), ('alerts_log', 'Alerts & Notifications Log')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='core.tenant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'report_type'], name='reporting_r_tenant__0439c0_idx'), models.Index(fields=['tenant', 'generated_at'], name='reporting_r_tenant__2409d3_idx')],
                'unique_together': {('tenant', 'report_number')},
            },
        ),
    ]
