# Generated by Django 4.2.29 on 2026-04-14 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehousing', '0001_initial'),
        ('lot_tracking', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCountSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='weekly', max_length=20)),
                ('abc_class', models.CharField(choices=[('a', 'Class A (High Value)'), ('b', 'Class B (Medium Value)'), ('c', 'Class C (Low Value)'), ('all', 'All Classes')], default='all', max_length=10)),
                ('next_run_date', models.DateField(blank=True, null=True)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cycle_count_schedules', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_schedules', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_schedules', to='warehousing.warehouse')),
                ('zones', models.ManyToManyField(blank=True, related_name='cycle_count_schedules', to='warehousing.zone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.CharField(max_length=20, verbose_name='Count Number')),
                ('type', models.CharField(choices=[('full', 'Full Physical Inventory'), ('cycle', 'Cycle Count'), ('spot', 'Spot Check')], default='cycle', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('counted', 'Counted'), ('reviewed', 'Reviewed'), ('adjusted', 'Adjusted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('blind_count', models.BooleanField(default=False, help_text='Hide expected system quantity from counters to prevent bias.')),
                ('scheduled_date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeze_number', models.CharField(max_length=20, verbose_name='Freeze Number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], default='active', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_freezes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_freezes', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_freezes', to='warehousing.warehouse')),
                ('zones', models.ManyToManyField(blank=True, related_name='stocktake_freezes', to='warehousing.zone')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'freeze_number')},
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.IntegerField(default=0, help_text='Expected quantity from system at snapshot time.')),
                ('counted_qty', models.IntegerField(blank=True, help_text='Actual counted quantity.', null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason_code', models.CharField(blank=True, choices=[('', '— Select —'), ('miscount', 'Miscount'), ('damage', 'Damage'), ('theft', 'Theft / Shrinkage'), ('misplaced', 'Misplaced / Wrong Bin'), ('data_error', 'Data Entry Error'), ('receiving_error', 'Receiving Error'), ('shipping_error', 'Shipping Error'), ('other', 'Other')], default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_items', to='warehousing.bin')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocktaking.stockcount')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_stock_count_items', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_items', to='lot_tracking.lotbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_items', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_items', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='stockcount',
            name='freeze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='stocktaking.stocktakefreeze'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='stocktaking.cyclecountschedule'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='warehousing.warehouse'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='warehousing.zone'),
        ),
        migrations.CreateModel(
            name='StockVarianceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(max_length=20, verbose_name='Adjustment Number')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason_code', models.CharField(choices=[('miscount', 'Miscount'), ('damage', 'Damage / Loss'), ('theft', 'Theft / Shrinkage'), ('data_error', 'Data Entry Error'), ('receiving_error', 'Receiving Error'), ('shipping_error', 'Shipping Error'), ('other', 'Other')], default='miscount', max_length=30)),
                ('total_variance_qty', models.IntegerField(default=0)),
                ('total_variance_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_variance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variance_adjustments', to='stocktaking.stockcount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_variance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variance_adjustments', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'adjustment_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stockcount',
            unique_together={('tenant', 'count_number')},
        ),
    ]
