# Generated by Django 4.2.29 on 2026-04-17 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcountitem',
            name='counted_qty',
            field=models.IntegerField(blank=True, help_text='Actual counted quantity. Non-negative.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
