# Generated by Django 4.2.29 on 2026-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_height_alter_product_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, default='', help_text='Harmonized System Nomenclature code (India GST, EU combined nomenclature).', max_length=20, verbose_name='HSN/SAC Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.CharField(choices=[('standard', 'Standard'), ('reduced', 'Reduced'), ('zero', 'Zero-rated'), ('exempt', 'Exempt')], default='standard', help_text='Tax category used by the accounting module to resolve jurisdictional tax rate.', max_length=20),
        ),
    ]
