# Generated by Django 4.2.29 on 2026-04-16 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='MOQ'),
        ),
        migrations.AlterField(
            model_name='vendorcontract',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vendorcontract',
            name='moq',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Order Quantity'),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='defect_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Defect rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='on_time_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='On-time delivery percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='vendorcontract',
            constraint=models.CheckConstraint(check=models.Q(('contract_value__gte', 0)), name='vendorcontract_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vendorperformance',
            constraint=models.CheckConstraint(check=models.Q(('delivery_rating__gte', 1), ('delivery_rating__lte', 5)), name='vendorperformance_delivery_rating_1_5'),
        ),
        migrations.AddConstraint(
            model_name='vendorperformance',
            constraint=models.CheckConstraint(check=models.Q(('quality_rating__gte', 1), ('quality_rating__lte', 5)), name='vendorperformance_quality_rating_1_5'),
        ),
        migrations.AddConstraint(
            model_name='vendorperformance',
            constraint=models.CheckConstraint(check=models.Q(('compliance_rating__gte', 1), ('compliance_rating__lte', 5)), name='vendorperformance_compliance_rating_1_5'),
        ),
        migrations.AddConstraint(
            model_name='vendorperformance',
            constraint=models.CheckConstraint(check=models.Q(('defect_rate__gte', 0), ('defect_rate__lte', 100)), name='vendorperformance_defect_rate_0_100'),
        ),
        migrations.AddConstraint(
            model_name='vendorperformance',
            constraint=models.CheckConstraint(check=models.Q(('on_time_delivery_rate__gte', 0), ('on_time_delivery_rate__lte', 100)), name='vendorperformance_on_time_rate_0_100'),
        ),
    ]
