"""Idempotent seed command for Module 18 — Reporting & Analytics.

For each active tenant, generates one `ReportSnapshot` of each registered report
type using the actual compute services against existing seeded data. Safe to
run multiple times without --flush.

Usage:
    python manage.py seed_reporting
    python manage.py seed_reporting --flush
"""
from datetime import date, timedelta
import json
from decimal import Decimal

from django.core.management.base import BaseCommand

from core.models import Tenant, User
from reporting.models import ReportSnapshot
from reporting.registry import REPORTS, resolve


def _json_default(value):
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, (date,)):
        return value.isoformat()
    return str(value)


class Command(BaseCommand):
    help = 'Seed reporting snapshots — one of each report type per tenant. Idempotent.'

    def add_arguments(self, parser):
        parser.add_argument('--flush', action='store_true',
                            help='Delete all existing ReportSnapshot rows before seeding.')

    def handle(self, *args, **options):
        tenants = Tenant.objects.filter(is_active=True)
        if not tenants.exists():
            self.stdout.write(self.style.WARNING(
                'No active tenants found. Run "python manage.py seed" first.'))
            return

        if options['flush']:
            deleted, _ = ReportSnapshot.objects.all().delete()
            self.stdout.write(self.style.SUCCESS(f'Flushed {deleted} existing snapshots.'))

        total_created = 0
        for tenant in tenants:
            if ReportSnapshot.objects.filter(tenant=tenant).exists():
                self.stdout.write(f'[{tenant.slug}] Snapshots already exist — skipping (use --flush to re-seed).')
                continue
            created = self._seed_tenant(tenant)
            total_created += created
            self.stdout.write(self.style.SUCCESS(f'[{tenant.slug}] Generated {created} snapshot(s).'))

        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS(f'Done. Total snapshots created: {total_created}'))
        self.stdout.write('')
        self.stdout.write(self.style.WARNING(
            "Log in as a tenant admin (e.g. admin_acme / demo123) to see reports. "
            "Superuser 'admin' has no tenant — reporting views return empty."))

    def _seed_tenant(self, tenant):
        generator = User.objects.filter(tenant=tenant, is_tenant_admin=True).first()
        created = 0
        period_end = date.today()
        period_start = period_end - timedelta(days=180)

        for slug, spec in REPORTS.items():
            try:
                service_fn = resolve(spec['service'])
            except Exception as exc:
                self.stdout.write(self.style.WARNING(f'  skip {slug}: {exc}'))
                continue

            # Pick params that fit the report's time model
            kwargs = {}
            if 'as_of_date' in spec.get('form', ''):
                pass  # nothing special — services default as_of_date to today
            if 'Period' in spec.get('form', '') or 'ABC' in spec.get('form', '') or 'Turnover' in spec.get('form', ''):
                kwargs.setdefault('period_start', period_start)
                kwargs.setdefault('period_end', period_end)

            try:
                result = service_fn(tenant, **kwargs)
            except Exception as exc:
                self.stdout.write(self.style.WARNING(f'  skip {slug}: compute error: {exc}'))
                continue

            params_for_save = {}
            if 'period_start' in kwargs:
                params_for_save['period_start'] = kwargs['period_start'].isoformat()
                params_for_save['period_end'] = kwargs['period_end'].isoformat()

            snap = ReportSnapshot(
                tenant=tenant,
                report_type=slug,
                title=spec['title'] + ' — Seeded Snapshot',
                as_of_date=date.today() if 'AsOf' in spec.get('form', '') or 'Valuation' in spec.get('form', '') or 'Aging' in spec.get('form', '') or 'LotExpiry' in spec.get('form', '') else None,
                period_start=kwargs.get('period_start'),
                period_end=kwargs.get('period_end'),
                parameters=params_for_save,
                summary=json.loads(json.dumps(result.get('summary', {}), default=_json_default)),
                data=json.loads(json.dumps(result.get('data', {}), default=_json_default)),
                generated_by=generator,
                notes='Auto-generated by seed_reporting.',
            )
            snap.save()
            created += 1
        return created
