# Generated by Django 4.2.29 on 2026-04-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehousing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, verbose_name='Location Code')),
                ('location_type', models.CharField(choices=[('company', 'Parent Company'), ('regional_dc', 'Regional Distribution Center'), ('distribution_center', 'Distribution Center'), ('retail_store', 'Retail Store'), ('warehouse', 'Warehouse')], default='retail_store', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('manager_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='multi_location.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.tenant')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Optional link to a physical warehouse for stock roll-up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LocationPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('markup_pct', 'Markup %'), ('markdown_pct', 'Markdown %'), ('fixed_adjustment', 'Fixed Price Adjustment'), ('override_price', 'Override Retail Price')], default='markup_pct', max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_pricing_rules', to='catalog.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='multi_location.location')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_pricing_rules', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pricing_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['location', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='LocationTransferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True)),
                ('max_transfer_qty', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('requires_approval', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transfer_rules', to='multi_location.location')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_transfer_rules', to='multi_location.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_transfer_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['source_location', 'priority'],
                'unique_together': {('tenant', 'source_location', 'destination_location')},
            },
        ),
        migrations.CreateModel(
            name='LocationSafetyStockRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_stock_qty', models.PositiveIntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('max_stock_qty', models.PositiveIntegerField(default=0, help_text='0 = no ceiling')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stock_rules', to='multi_location.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_safety_stock_rules', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_safety_stock_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['location', 'product'],
                'unique_together': {('tenant', 'location', 'product')},
            },
        ),
    ]
