# Generated by Django 4.2.29 on 2026-04-18 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Code must be uppercase letters, digits, and dashes only; must start with a letter or digit.', regex='^[A-Z0-9][A-Z0-9\\-]*$')], verbose_name='Location Code'),
        ),
    ]
