# Generated by Django 4.2.29 on 2026-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_salesorderitem_discount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'warehouse', 'order_date'], name='orders_sale_tenant__ef89f7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['tenant', 'product'], name='orders_sale_tenant__d174e2_idx'),
        ),
    ]
