# Generated by Django 4.2.29 on 2026-04-21 19:44

import core.state_machine
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_forecasting_indexes'),
        ('core', '0001_initial'),
        ('catalog', '0003_product_hsn_code_product_tax_category'),
        ('vendors', '0002_alter_vendor_minimum_order_quantity_and_more'),
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_orders', '0002_purchaseorderdispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='APBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, verbose_name='Bill #')),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_terms', models.CharField(blank=True, default='net_30', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('paid', 'Paid'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_bills_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bill_date', '-id'],
            },
            bases=(core.state_machine.StateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ARInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='Invoice #')),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_terms', models.CharField(blank=True, default='net_30', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
            bases=(core.state_machine.StateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Account Code')),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.CharField(max_length=20, verbose_name='Period #')),
                ('name', models.CharField(help_text='e.g., "FY2026-Q1", "Apr 2026"', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date'],
            },
            bases=(core.state_machine.StateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=20, verbose_name='JE #')),
                ('entry_date', models.DateField()),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('ap_bill', 'AP Bill'), ('ar_invoice', 'AR Invoice'), ('stock_adjustment', 'Stock Adjustment'), ('scrap_writeoff', 'Scrap Write-Off'), ('valuation', 'Inventory Valuation')], default='manual', max_length=20)),
                ('source_reference', models.CharField(blank=True, default='', help_text='Denormalized source number, e.g. "BIL-00001".', max_length=40)),
                ('source_id', models.CharField(blank=True, default='', help_text='Source model pk as string.', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fiscalperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_posted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entry_date', '-id'],
            },
            bases=(core.state_machine.StateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaxJurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., "US", "US-CA", "IN", "GB", "EU"', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_jurisdictions', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tax Jurisdiction',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
            ],
            options={
                'ordering': ['line_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=20, verbose_name='Customer #')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('billing_address', models.TextField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('tax_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Tax ID (GST/VAT)')),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('net_90', 'Net 90'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid')], default='net_30', max_length=20)),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_customers', to='core.tenant')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ARInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('line_order', models.PositiveIntegerField(default=0)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.arinvoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product')),
            ],
            options={
                'ordering': ['line_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.customer'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoices', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='source_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoices', to='orders.shipment'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='source_so',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoices', to='orders.salesorder'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_invoices', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='APBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('line_order', models.PositiveIntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.apbill')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product')),
            ],
            options={
                'ordering': ['line_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='apbill',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_bills', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='apbill',
            name='source_grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_bills', to='receiving.goodsreceiptnote'),
        ),
        migrations.AddField(
            model_name='apbill',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_bills', to='receiving.vendorinvoice'),
        ),
        migrations.AddField(
            model_name='apbill',
            name='source_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_bills', to='purchase_orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='apbill',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_bills', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='apbill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_bills', to='vendors.vendor'),
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_number', models.CharField(max_length=20, verbose_name='Rule #')),
                ('tax_category', models.CharField(choices=[('standard', 'Standard'), ('reduced', 'Reduced'), ('zero', 'Zero-rated'), ('exempt', 'Exempt')], default='standard', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Rate as percentage (e.g. 10.00 for 10%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounting.taxjurisdiction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['-effective_date', 'jurisdiction__code', 'tax_category'],
                'unique_together': {('tenant', 'rule_number')},
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__9f3b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'source_type', 'source_id'], name='accounting__tenant__4b06cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('tenant', 'entry_number')},
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('tenant', 'period_number')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'customer_number')},
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='arinvoice',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__2e0f06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='arinvoice',
            unique_together={('tenant', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='apbill',
            index=models.Index(fields=['tenant', 'status'], name='accounting__tenant__b1ac73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apbill',
            unique_together={('tenant', 'bill_number')},
        ),
    ]
