# Generated by Django 4.2.29 on 2026-04-04 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_method', models.CharField(choices=[('email', 'Email'), ('edi', 'EDI (Electronic Data Interchange)'), ('manual', 'Manual / Hand Delivery'), ('other', 'Other')], default='email', max_length=20)),
                ('sent_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='purchase_orders.purchaseorder')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_dispatches', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_dispatches', to='core.tenant')),
            ],
            options={
                'ordering': ['-dispatched_at'],
            },
        ),
    ]
