# Generated by Django 4.2.29 on 2026-04-16 18:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehousing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_number', models.CharField(max_length=20, verbose_name='Forecast Number')),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('moving_avg', 'Moving Average'), ('exp_smoothing', 'Exponential Smoothing'), ('linear_regression', 'Linear Regression'), ('seasonal', 'Seasonal (Moving Avg × Seasonality)')], default='moving_avg', max_length=30)),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('history_periods', models.PositiveIntegerField(default=6, help_text='Number of past periods to use for calculation.')),
                ('forecast_periods', models.PositiveIntegerField(default=3, help_text='Number of future periods to project.')),
                ('confidence_pct', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Estimated confidence in forecast (0–100).', max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demand_forecasts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_forecasts', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('period_type', models.CharField(choices=[('month', 'Monthly (12 Periods)'), ('quarter', 'Quarterly (4 Periods)')], default='month', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasonality_profiles', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seasonality_profiles', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasonality_profiles', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_profiles', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReorderPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_daily_usage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average units consumed per day.', max_digits=10)),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='Vendor lead time in days.')),
                ('safety_stock_qty', models.PositiveIntegerField(default=0)),
                ('rop_qty', models.PositiveIntegerField(default=0, help_text='ROP = (avg_daily_usage × lead_time_days) + safety_stock_qty.')),
                ('min_qty', models.PositiveIntegerField(default=0)),
                ('max_qty', models.PositiveIntegerField(default=0)),
                ('reorder_qty', models.PositiveIntegerField(default=0, help_text='Standard replenishment quantity (EOQ or fixed).')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_points', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_points', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_points', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['product__name', 'warehouse__name'],
                'unique_together': {('tenant', 'product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='DemandForecastLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_index', models.IntegerField(help_text='Negative = history, zero/positive = future.')),
                ('period_label', models.CharField(help_text='e.g. "Jan 2026", "Q1 2026", "W12-2026".', max_length=30)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('historical_qty', models.IntegerField(blank=True, null=True)),
                ('forecast_qty', models.IntegerField(blank=True, null=True)),
                ('adjusted_qty', models.IntegerField(blank=True, help_text='Forecast qty after seasonality multiplier.', null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forecasting.demandforecast')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecast_lines', to='core.tenant')),
            ],
            options={
                'ordering': ['forecast', 'period_index'],
            },
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='seasonality_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_forecasts', to='forecasting.seasonalityprofile'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_forecasts', to='warehousing.warehouse'),
        ),
        migrations.CreateModel(
            name='SeasonalityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveSmallIntegerField(help_text='1–12 for month, 1–4 for quarter.')),
                ('period_label', models.CharField(max_length=20)),
                ('demand_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier applied to forecast qty (1.00 = baseline).', max_digits=5)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='forecasting.seasonalityprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_periods', to='core.tenant')),
            ],
            options={
                'ordering': ['profile', 'period_number'],
                'unique_together': {('profile', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='SafetyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('fixed', 'Fixed Quantity'), ('statistical', 'Statistical (Service Level)'), ('percentage', 'Percentage of Demand')], default='statistical', max_length=20)),
                ('service_level', models.DecimalField(decimal_places=3, default=Decimal('0.950'), help_text='Target service level (e.g. 0.95 = 95%).', max_digits=5)),
                ('avg_demand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average daily demand.', max_digits=12)),
                ('demand_std_dev', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard deviation of daily demand.', max_digits=12)),
                ('avg_lead_time_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('lead_time_std_dev', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fixed_qty', models.PositiveIntegerField(default=0, help_text='Used when method = Fixed.')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Percent of avg lead-time demand (used when method = Percentage).', max_digits=5)),
                ('safety_stock_qty', models.PositiveIntegerField(default=0, help_text='Calculated safety stock quantity.')),
                ('notes', models.TextField(blank=True, default='')),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stocks', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stocks', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stocks', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['product__name', 'warehouse__name'],
                'unique_together': {('tenant', 'product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='ReorderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_number', models.CharField(max_length=20, verbose_name='Alert Number')),
                ('current_qty', models.IntegerField(default=0)),
                ('rop_qty', models.PositiveIntegerField(default=0)),
                ('suggested_order_qty', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('ordered', 'Ordered'), ('closed', 'Closed')], default='new', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_reorder_alerts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_alerts', to='catalog.product')),
                ('rop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='forecasting.reorderpoint')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_alerts', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_alerts', to='warehousing.warehouse')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'unique_together': {('tenant', 'alert_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='demandforecast',
            unique_together={('tenant', 'forecast_number')},
        ),
    ]
