# Generated by Django 4.2.29 on 2026-04-18 19:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandforecast',
            name='confidence_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Estimated confidence in forecast (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='forecast_periods',
            field=models.PositiveIntegerField(default=3, help_text='Number of future periods to project.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='history_periods',
            field=models.PositiveIntegerField(default=6, help_text='Number of past periods to use for calculation.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)]),
        ),
        migrations.AlterField(
            model_name='reorderpoint',
            name='avg_daily_usage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average units consumed per day.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='safetystock',
            name='avg_demand',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average daily demand.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='safetystock',
            name='avg_lead_time_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='safetystock',
            name='demand_std_dev',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard deviation of daily demand.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='safetystock',
            name='lead_time_std_dev',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='safetystock',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Percent of avg lead-time demand (used when method = Percentage).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='safetystock',
            name='service_level',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.950'), help_text='Target service level (e.g. 0.95 = 95%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('0.999'))]),
        ),
        migrations.AlterField(
            model_name='seasonalityperiod',
            name='demand_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier applied to forecast qty (1.00 = baseline).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
